# Daylight Conversion (the amount of daylight in a day is returned in seconds)
DAYLIGHT_HOUR_DIVISOR = 3600

# Decimal Rounding
DECIMAL_PLACES = 1

PROPERTY_CRIMES = {
    "ARSON",
    "BURGLARY",
    "BURGLAR'S TOOLS",
    "CRIMINAL MISCHIEF & RELATED OF",
    "CRIMINAL TRESPASS",
    "FORGERY",
    "FRAUDS",
    "GRAND LARCENY",
    "GRAND LARCENY OF MOTOR VEHICLE",
    "OTHER OFFENSES RELATED TO THEFT",
    "PETIT LARCENY",
    "PETIT LARCENY OF MOTOR VEHICLE",
    "POSSESSION OF STOLEN PROPERTY",
    "THEFT OF SERVICES",
    "THEFT-FRAUD",
    "UNAUTHORIZED USE OF A VEHICLE"
}

VIOLENT_CRIMES = {
    "ASSAULT 3 & RELATED OFFENSES",
    "FELONY ASSAULT",
    "HOMICIDE & RELATED OFFENSES",
    "HOMICIDE-NEGLIGENT,UNCLASSIFIE",
    "HOMICIDE-NEGLIGENT-VEHICLE",
    "KIDNAPPING & RELATED OFFENSES",
    "OFFENSES AGAINST THE PERSON",
    "RAPE",
    "ROBBERY",
    "SEX CRIMES",
    "DANGEROUS WEAPONS",
    
    "MURDER & NON-NEGL. MANSLAUGHTER"
}

PUBLIC_ORDER_CRIMES = {
    "ADMINISTRATIVE CODE",
    "AGRICULTURE & MRKTS LAW-UNCLASSIFIED",
    "ALCOHOLIC BEVERAGE CONTROL LAW",
    "ANTICIPATORY OFFENSES",
    "CANNABIS RELATED OFFENSES",
    "CHILD ABANDONMENT/NON SUPPORT",
    "DANGEROUS DRUGS",
    "UNLAWFUL POSS. WEAP. ON SCHOOL",
    "DISORDERLY CONDUCT",
    "EDUCATION LAW-UNCLASSIFIED",
    "MISCELLANEOUS PENAL LAW",
    "NYS LAWS-UNCLASSIFIED FELONY",
    "ENDAN WELFARE INCOMP",
    "ESCAPE 3",
    "GAMBLING",
    "HARRASSMENT 2",
    "INTOXICATED & IMPAIRED DRIVING",
    "JOSTLING",
    "LOITERING",
    "OFF. AGNST PUB ORD SENSBLTY &",
    "OFFENSES AGAINST PUBLIC ADMINI",
    "OFFENSES INVOLVING FRAUD",
    "OFFENSES RELATED TO CHILDREN",
    "OTHER OFFENSES RELATED TO THEF",
    "OTHER STATE LAWS",
    "OTHER STATE LAWS (NON PENAL LA",
    "OTHER STATE LAWS (NON PENAL LAW)",
    "PROSTITUTION & RELATED OFFENSES",
    "VEHICLE AND TRAFFIC LAWS"
}

PROPERTY_KEYWORDS = {
    "FORGERY",
    "UNAUTHORIZED",
    "STOLEN",
    "THEFT",
    "LARCENY"
}

VIOLENT_KEYWORDS = {
    "ASSAULT",
    "MENACING",
    "ENDANGERMENT",
    "THREAT", 
    "CONTEMPT", 
    "KIDNAPPING", 
    "RAPE", 
    "SEX", 
    "WEAPON",
    "MURDER",
    "MANSLAUGHTER",
    "CRIMINAL",
    "RECKLESS",
    "TERRORISM",
    "THREAT"
}